### PR TITLE
using std::optional in favor of bool return

### PR DESCRIPTION
**Pull request by sbrkopac**
# Pull Request Template

## Description

Utilizing std::optional rather than a bool check for returning a user value. This allows the library to transform code from:
```
int value;
if(object->getValue("foo", value))
{
}
```
Into its c++17 equivalent:
```
auto value = object->getValue("foo");
if(value)
{
}
```

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sbrkopac** [comment]
I also tagged in a fix for a typo. Let me know if I need to open a new PR for that.

**Comment by openscenegraph** [comment]
This won't work.  I had to remove std::optionall use elsewhere due to portability issues.

**Comment by sbrkopac** [comment]
Portability issues from where?

**Comment by vsg-dev** [comment]
I think @tomhog found issues with std::optional on either the Android port.  The line of least resistance was simply to replace the std::optional usage.

Could you generate a PR for the typo fix. Thanks.

**Comment by vsg-dev** [comment]
I'm closing this PR as it risks cross platform build.  I have applied the typo fix:

https://github.com/vsg-dev/VulkanSceneGraphPrototype/commit/5d05f3f13f93a762c06c89407ab4fdab180001eb

**Comment by sbrkopac** [comment]
I know it's difficult with the speed at which you are prototyping, but is it possible to have a blurb somewhere about the different c++17 features that can't be used due to X reason?

**Comment by vsg-dev** [comment]
I have wondered about writing a C++ usage document, from the perspective of what bits of C++17 etc. are used where, but adding what parts don't currently work well across platforms would be a good addition too.  I can't promise this right away but I'll continue thinking about it.

**Comment by tomhog** [comment]
Hi @sbrkopac 

So the issue at the moment is on macOS std::optional and std::any are currently in the std::experimental namespace (I'm assuming it'll be the same for iOS). So for now we've avoided them to prevent the code requiring conditional compilation in lots of places.

Hopefully apply move these into the standard std namespace in the near future.

**Pull request closed without merging**
